
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.farm
{ 
    public enum ESeedType
    {
        /// <summary>
        /// 通常作物
        /// </summary>
        Normal = 0,
        /// <summary>
        /// 水田作物
        /// </summary>
        Paddy = 1,
        /// <summary>
        /// 旱地作物
        /// </summary>
        Dry = 2,
        /// <summary>
        /// 盐碱地作物
        /// </summary>
        Saline = 3,
        /// <summary>
        /// 高营养作物
        /// </summary>
        Rich = 4,
        /// <summary>
        /// 耐酸作物
        /// </summary>
        Acid = 5,
        /// <summary>
        /// 特殊作物
        /// </summary>
        Special = 6,
        /// <summary>
        /// 药用作物
        /// </summary>
        Medicinal = 7,
    }

} 

