
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.farm
{ 
    public enum ELandType
    {
        /// <summary>
        /// 未解锁
        /// </summary>
        Lock = 0,
        /// <summary>
        /// 解锁中
        /// </summary>
        Unlocking = 1,
        /// <summary>
        /// 普通
        /// </summary>
        Normal = 2,
        /// <summary>
        /// 黑土地
        /// </summary>
        Black = 3,
        /// <summary>
        /// 红土地
        /// </summary>
        Red = 4,
        /// <summary>
        /// 黄土地
        /// </summary>
        Yellow = 5,
        /// <summary>
        /// 水田地
        /// </summary>
        Paddy = 6,
        /// <summary>
        /// 盐碱地
        /// </summary>
        Saline = 7,
        /// <summary>
        /// 壤土
        /// </summary>
        Loam = 8,
        /// <summary>
        /// 沙土地
        /// </summary>
        Sandy = 9,
        /// <summary>
        /// 碎石地
        /// </summary>
        Rocky = 10,
    }

} 

