
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Fry : ItemBase
{
    public Fry(ByteBuf _buf)  : base(_buf) 
    {
        GrowTime = _buf.ReadInt();
    }

    public static Fry DeserializeFry(ByteBuf _buf)
    {
        return new Fry(_buf);
    }

    public readonly int GrowTime;
   
    public const int __ID__ = 70925;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "quality:" + Quality + ","
        + "price:" + Price + ","
        + "desc:" + Desc + ","
        + "growTime:" + GrowTime + ","
        + "}";
    }
}

}

