
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Global : Luban.BeanBase
{
    public Global(ByteBuf _buf) 
    {
        PlayerInitLv = _buf.ReadInt();
        PlayerInitExp = _buf.ReadInt();
    }

    public static Global DeserializeGlobal(ByteBuf _buf)
    {
        return new Global(_buf);
    }

    /// <summary>
    /// 玩家初始等级
    /// </summary>
    public readonly int PlayerInitLv;
    /// <summary>
    /// 玩家初始经验
    /// </summary>
    public readonly int PlayerInitExp;
   
    public const int __ID__ = 2135814083;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "PlayerInitLv:" + PlayerInitLv + ","
        + "PlayerInitExp:" + PlayerInitExp + ","
        + "}";
    }
}

}

