
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
public partial class TbFishProduct
{
    private readonly System.Collections.Generic.Dictionary<int, FishProduct> _dataMap;
    private readonly System.Collections.Generic.List<FishProduct> _dataList;
    
    public TbFishProduct(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, FishProduct>();
        _dataList = new System.Collections.Generic.List<FishProduct>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            FishProduct _v;
            _v = FishProduct.DeserializeFishProduct(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, FishProduct> DataMap => _dataMap;
    public System.Collections.Generic.List<FishProduct> DataList => _dataList;

    public FishProduct GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public FishProduct Get(int key) => _dataMap[key];
    public FishProduct this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

