
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
public partial class TbDepester
{
    private readonly System.Collections.Generic.Dictionary<int, item.Depester> _dataMap;
    private readonly System.Collections.Generic.List<item.Depester> _dataList;
    
    public TbDepester(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, item.Depester>();
        _dataList = new System.Collections.Generic.List<item.Depester>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            item.Depester _v;
            _v = item.Depester.DeserializeDepester(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, item.Depester> DataMap => _dataMap;
    public System.Collections.Generic.List<item.Depester> DataList => _dataList;

    public item.Depester GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public item.Depester Get(int key) => _dataMap[key];
    public item.Depester this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

