
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public abstract partial class ItemBase : Luban.BeanBase
{
    public ItemBase(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Quality = _buf.ReadInt();
        Price = _buf.ReadInt();
        Desc = _buf.ReadString();
    }

    public static ItemBase DeserializeItemBase(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case ByProduct.__ID__: return new ByProduct(_buf);
            case CommonItem.__ID__: return new CommonItem(_buf);
            case Crops.__ID__: return new Crops(_buf);
            case Cub.__ID__: return new Cub(_buf);
            case item.Depester.__ID__: return new item.Depester(_buf);
            case item.Fertilizer.__ID__: return new item.Fertilizer(_buf);
            case Fish.__ID__: return new Fish(_buf);
            case FishProduct.__ID__: return new FishProduct(_buf);
            case Forniture.__ID__: return new Forniture(_buf);
            case Fry.__ID__: return new Fry(_buf);
            case Livestock.__ID__: return new Livestock(_buf);
            case RanchProduct.__ID__: return new RanchProduct(_buf);
            case Seasoning.__ID__: return new Seasoning(_buf);
            case Seed.__ID__: return new Seed(_buf);
            default: throw new SerializationException();
        }
    }

    public readonly int Id;
    public readonly string Name;
    public readonly int Quality;
    public readonly int Price;
    public readonly string Desc;
   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "quality:" + Quality + ","
        + "price:" + Price + ","
        + "desc:" + Desc + ","
        + "}";
    }
}

}

