
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
/// <summary>
/// 牲畜
/// </summary>
public partial class TbLivestock
{
    private readonly System.Collections.Generic.Dictionary<int, Livestock> _dataMap;
    private readonly System.Collections.Generic.List<Livestock> _dataList;
    
    public TbLivestock(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Livestock>();
        _dataList = new System.Collections.Generic.List<Livestock>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Livestock _v;
            _v = Livestock.DeserializeLivestock(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Livestock> DataMap => _dataMap;
    public System.Collections.Generic.List<Livestock> DataList => _dataList;

    public Livestock GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Livestock Get(int key) => _dataMap[key];
    public Livestock this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

