
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
public partial class TbItemBase
{
    private readonly System.Collections.Generic.Dictionary<int, ItemBase> _dataMap;
    private readonly System.Collections.Generic.List<ItemBase> _dataList;
    
    public TbItemBase(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ItemBase>();
        _dataList = new System.Collections.Generic.List<ItemBase>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ItemBase _v;
            _v = ItemBase.DeserializeItemBase(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ItemBase> DataMap => _dataMap;
    public System.Collections.Generic.List<ItemBase> DataList => _dataList;

    public T GetOrDefaultAs<T>(int key) where T : ItemBase => _dataMap.TryGetValue(key, out var v) ? (T)v : null;
    public T GetAs<T>(int key) where T : ItemBase => (T)_dataMap[key];
    public ItemBase GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ItemBase Get(int key) => _dataMap[key];
    public ItemBase this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

