
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
public partial class TbSeed
{
    private readonly System.Collections.Generic.Dictionary<int, Seed> _dataMap;
    private readonly System.Collections.Generic.List<Seed> _dataList;
    
    public TbSeed(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Seed>();
        _dataList = new System.Collections.Generic.List<Seed>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Seed _v;
            _v = Seed.DeserializeSeed(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Seed> DataMap => _dataMap;
    public System.Collections.Generic.List<Seed> DataList => _dataList;

    public Seed GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Seed Get(int key) => _dataMap[key];
    public Seed this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

