
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Livestock : ItemBase
{
    public Livestock(ByteBuf _buf)  : base(_buf) 
    {
        MeatId = _buf.ReadInt();
        MeatCount = _buf.ReadInt();
        ByproductId = _buf.ReadInt();
        ByproductCount = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ByproductTime = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); ByproductTime.Add(_e0);}}
    }

    public static Livestock DeserializeLivestock(ByteBuf _buf)
    {
        return new Livestock(_buf);
    }

    public readonly int MeatId;
    public readonly int MeatCount;
    public readonly int ByproductId;
    public readonly int ByproductCount;
    public readonly System.Collections.Generic.List<int> ByproductTime;
   
    public const int __ID__ = -1263527542;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "quality:" + Quality + ","
        + "price:" + Price + ","
        + "desc:" + Desc + ","
        + "meatId:" + MeatId + ","
        + "meatCount:" + MeatCount + ","
        + "byproductId:" + ByproductId + ","
        + "byproductCount:" + ByproductCount + ","
        + "byproductTime:" + Luban.StringUtil.CollectionToString(ByproductTime) + ","
        + "}";
    }
}

}

