
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.site
{
public partial class TbFarmlandType
{
    private readonly System.Collections.Generic.Dictionary<farm.ELandType, FarmlandType> _dataMap;
    private readonly System.Collections.Generic.List<FarmlandType> _dataList;
    
    public TbFarmlandType(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<farm.ELandType, FarmlandType>();
        _dataList = new System.Collections.Generic.List<FarmlandType>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            FarmlandType _v;
            _v = FarmlandType.DeserializeFarmlandType(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.LandType, _v);
        }
    }

    public System.Collections.Generic.Dictionary<farm.ELandType, FarmlandType> DataMap => _dataMap;
    public System.Collections.Generic.List<FarmlandType> DataList => _dataList;

    public FarmlandType GetOrDefault(farm.ELandType key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public FarmlandType Get(farm.ELandType key) => _dataMap[key];
    public FarmlandType this[farm.ELandType key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

