
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Worker : Luban.BeanBase
{
    public Worker(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Quality = _buf.ReadInt();
        Desc = _buf.ReadString();
        Mgmt = _buf.ReadInt();
        Cook = _buf.ReadInt();
        Research = _buf.ReadInt();
        Farm = _buf.ReadInt();
        Ranch = _buf.ReadInt();
        Fishing = _buf.ReadInt();
    }

    public static Worker DeserializeWorker(ByteBuf _buf)
    {
        return new Worker(_buf);
    }

    public readonly int Id;
    public readonly string Name;
    public readonly int Quality;
    public readonly string Desc;
    public readonly int Mgmt;
    public readonly int Cook;
    public readonly int Research;
    public readonly int Farm;
    public readonly int Ranch;
    public readonly int Fishing;
   
    public const int __ID__ = -1698218082;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "quality:" + Quality + ","
        + "desc:" + Desc + ","
        + "mgmt:" + Mgmt + ","
        + "cook:" + Cook + ","
        + "research:" + Research + ","
        + "farm:" + Farm + ","
        + "ranch:" + Ranch + ","
        + "fishing:" + Fishing + ","
        + "}";
    }
}

}

