
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
/// <summary>
/// 调味品
/// </summary>
public partial class TbSeasoning
{
    private readonly System.Collections.Generic.Dictionary<int, Seasoning> _dataMap;
    private readonly System.Collections.Generic.List<Seasoning> _dataList;
    
    public TbSeasoning(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Seasoning>();
        _dataList = new System.Collections.Generic.List<Seasoning>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Seasoning _v;
            _v = Seasoning.DeserializeSeasoning(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Seasoning> DataMap => _dataMap;
    public System.Collections.Generic.List<Seasoning> DataList => _dataList;

    public Seasoning GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Seasoning Get(int key) => _dataMap[key];
    public Seasoning this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

