
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Item : Luban.BeanBase
{
    public Item(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Quality = (item.EQuality)_buf.ReadInt();
        Kind = (item.EFornitureType)_buf.ReadInt();
        Desc = _buf.ReadString();
        Price = _buf.ReadInt();
    }

    public static Item DeserializeItem(ByteBuf _buf)
    {
        return new Item(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly item.EQuality Quality;
    /// <summary>
    /// 家具类型
    /// </summary>
    public readonly item.EFornitureType Kind;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
   
    public const int __ID__ = 2289459;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "quality:" + Quality + ","
        + "kind:" + Kind + ","
        + "desc:" + Desc + ","
        + "price:" + Price + ","
        + "}";
    }
}

}

