
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Livestock : Luban.BeanBase
{
    public Livestock(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Quality = (item.EQuality)_buf.ReadInt();
        Desc = _buf.ReadString();
        Price = _buf.ReadInt();
        Meat = _buf.ReadInt();
        MeatCount = _buf.ReadInt();
        Byproduct = _buf.ReadInt();
        ByproductTime = _buf.ReadInt();
    }

    public static Livestock DeserializeLivestock(ByteBuf _buf)
    {
        return new Livestock(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly item.EQuality Quality;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 宰杀后所得物品
    /// </summary>
    public readonly int Meat;
    /// <summary>
    /// 宰杀后物品数量
    /// </summary>
    public readonly int MeatCount;
    /// <summary>
    /// 副产品
    /// </summary>
    public readonly int Byproduct;
    /// <summary>
    /// 副产品产生时间
    /// </summary>
    public readonly int ByproductTime;
   
    public const int __ID__ = -1263527542;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "quality:" + Quality + ","
        + "desc:" + Desc + ","
        + "price:" + Price + ","
        + "meat:" + Meat + ","
        + "meatCount:" + MeatCount + ","
        + "byproduct:" + Byproduct + ","
        + "byproductTime:" + ByproductTime + ","
        + "}";
    }
}

}

