
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.character
{
/// <summary>
/// 雇员
/// </summary>
public partial class TbWorker
{
    private readonly System.Collections.Generic.Dictionary<int, Worker> _dataMap;
    private readonly System.Collections.Generic.List<Worker> _dataList;
    
    public TbWorker(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Worker>();
        _dataList = new System.Collections.Generic.List<Worker>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Worker _v;
            _v = Worker.DeserializeWorker(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Worker> DataMap => _dataMap;
    public System.Collections.Generic.List<Worker> DataList => _dataList;

    public Worker GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Worker Get(int key) => _dataMap[key];
    public Worker this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

