
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.common
{
public partial class TbModule
{
    private readonly System.Collections.Generic.Dictionary<int, PlayModule> _dataMap;
    private readonly System.Collections.Generic.List<PlayModule> _dataList;
    
    public TbModule(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, PlayModule>();
        _dataList = new System.Collections.Generic.List<PlayModule>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            PlayModule _v;
            _v = PlayModule.DeserializePlayModule(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, PlayModule> DataMap => _dataMap;
    public System.Collections.Generic.List<PlayModule> DataList => _dataList;

    public PlayModule GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public PlayModule Get(int key) => _dataMap[key];
    public PlayModule this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

