
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Cub : ItemBase
{
    public Cub(ByteBuf _buf)  : base(_buf) 
    {
        GrowTime = _buf.ReadInt();
        MeatId = _buf.ReadInt();
        MeatCount = _buf.ReadInt();
    }

    public static Cub DeserializeCub(ByteBuf _buf)
    {
        return new Cub(_buf);
    }

    public readonly int GrowTime;
    public readonly int MeatId;
    public readonly int MeatCount;
   
    public const int __ID__ = 68112;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "quality:" + Quality + ","
        + "price:" + Price + ","
        + "desc:" + Desc + ","
        + "growTime:" + GrowTime + ","
        + "meatId:" + MeatId + ","
        + "meatCount:" + MeatCount + ","
        + "}";
    }
}

}

