
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum EGameModule
    {
        /// <summary>
        /// 农场模块
        /// </summary>
        Farmland = 1,
        /// <summary>
        /// 牧场模块
        /// </summary>
        Ranchland = 2,
        /// <summary>
        /// 渔场模块
        /// </summary>
        Fishland = 3,
    }

} 

