
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum EItemType
    {
        /// <summary>
        /// 通用道具
        /// </summary>
        Common = 0,
        /// <summary>
        /// 种子
        /// </summary>
        Seed = 1,
        /// <summary>
        /// 农作物
        /// </summary>
        Crop = 2,
        /// <summary>
        /// 肥料
        /// </summary>
        Fertilizer = 3,
        /// <summary>
        /// 杀虫剂
        /// </summary>
        DePester = 4,
        /// <summary>
        /// 幼崽
        /// </summary>
        Cub = 5,
        /// <summary>
        /// 牲畜
        /// </summary>
        Livestock = 6,
        /// <summary>
        /// 牧场产品
        /// </summary>
        RanchProduct = 7,
        /// <summary>
        /// 牧场副产品
        /// </summary>
        RanchByProduct = 8,
        /// <summary>
        /// 鱼苗
        /// </summary>
        Fry = 9,
        /// <summary>
        /// 鱼
        /// </summary>
        Fish = 10,
        /// <summary>
        /// 渔场产品
        /// </summary>
        FishProduct = 11,
        /// <summary>
        /// 雇员
        /// </summary>
        Worker = 12,
        /// <summary>
        /// 家具
        /// </summary>
        Forniture = 13,
    }

} 

