
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum EQuality
    {
        /// <summary>
        /// 白
        /// </summary>
        WHITE = 0,
        /// <summary>
        /// 绿
        /// </summary>
        GREEN = 1,
        /// <summary>
        /// 蓝
        /// </summary>
        BLUE = 2,
        /// <summary>
        /// 紫
        /// </summary>
        PURPLE = 3,
        /// <summary>
        /// 黄
        /// </summary>
        YELLOW = 4,
        /// <summary>
        /// 红
        /// </summary>
        RED = 5,
    }

} 

