
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class ErrorCode : Luban.BeanBase
{
    public ErrorCode(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Req = _buf.ReadString();
        Resp = _buf.ReadString();
        FuncDesc = _buf.ReadString();
        Errorcode0 = _buf.ReadString();
        Errorcode1 = _buf.ReadString();
        Errorcode2 = _buf.ReadString();
        Errorcode3 = _buf.ReadString();
        Errorcode4 = _buf.ReadString();
        Errorcode5 = _buf.ReadString();
    }

    public static ErrorCode DeserializeErrorCode(ByteBuf _buf)
    {
        return new ErrorCode(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 请求协议名
    /// </summary>
    public readonly string Req;
    /// <summary>
    /// 返回协议名
    /// </summary>
    public readonly string Resp;
    /// <summary>
    /// 功能描述
    /// </summary>
    public readonly string FuncDesc;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Errorcode0;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Errorcode1;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Errorcode2;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Errorcode3;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Errorcode4;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Errorcode5;
   
    public const int __ID__ = -1961963531;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "req:" + Req + ","
        + "resp:" + Resp + ","
        + "funcDesc:" + FuncDesc + ","
        + "errorcode0:" + Errorcode0 + ","
        + "errorcode1:" + Errorcode1 + ","
        + "errorcode2:" + Errorcode2 + ","
        + "errorcode3:" + Errorcode3 + ","
        + "errorcode4:" + Errorcode4 + ","
        + "errorcode5:" + Errorcode5 + ","
        + "}";
    }
}

}

