
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class FarmlandType : Luban.BeanBase
{
    public FarmlandType(ByteBuf _buf) 
    {
        LandType = (farm.ELandType)_buf.ReadInt();
        Name = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Cost = new System.Collections.Generic.List<item.ItemExchange>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { item.ItemExchange _e0;  _e0 = item.ItemExchange.DeserializeItemExchange(_buf); Cost.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Friendly = new System.Collections.Generic.HashSet<farm.ESeedType>(/*n0 * 3 / 2*/);for(var i0 = 0 ; i0 < n0 ; i0++) { farm.ESeedType _e0;  _e0 = (farm.ESeedType)_buf.ReadInt(); Friendly.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);General = new System.Collections.Generic.HashSet<farm.ESeedType>(/*n0 * 3 / 2*/);for(var i0 = 0 ; i0 < n0 ; i0++) { farm.ESeedType _e0;  _e0 = (farm.ESeedType)_buf.ReadInt(); General.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Hostile = new System.Collections.Generic.HashSet<farm.ESeedType>(/*n0 * 3 / 2*/);for(var i0 = 0 ; i0 < n0 ; i0++) { farm.ESeedType _e0;  _e0 = (farm.ESeedType)_buf.ReadInt(); Hostile.Add(_e0);}}
        GrowTimeBuff = _buf.ReadInt();
        YieldCountBuff = _buf.ReadInt();
        RareRateBuff = _buf.ReadInt();
        WaterBuff = _buf.ReadInt();
        WaterCountBuff = _buf.ReadInt();
        FertilizerBuff = _buf.ReadInt();
        FertilizerCountBuff = _buf.ReadInt();
        PestRateBuff = _buf.ReadInt();
        Desc = _buf.ReadString();
    }

    public static FarmlandType DeserializeFarmlandType(ByteBuf _buf)
    {
        return new FarmlandType(_buf);
    }

    /// <summary>
    /// 土地类型
    /// </summary>
    public readonly farm.ELandType LandType;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly System.Collections.Generic.List<item.ItemExchange> Cost;
    /// <summary>
    /// 友好作物类型
    /// </summary>
    public readonly System.Collections.Generic.HashSet<farm.ESeedType> Friendly;
    /// <summary>
    /// 一般作物类型
    /// </summary>
    public readonly System.Collections.Generic.HashSet<farm.ESeedType> General;
    /// <summary>
    /// 不友好作物类型
    /// </summary>
    public readonly System.Collections.Generic.HashSet<farm.ESeedType> Hostile;
    /// <summary>
    /// 种植时间变化，可以是负数，1代表 +1%
    /// </summary>
    public readonly int GrowTimeBuff;
    /// <summary>
    /// 产量变化，可以是负数，1代表 +1%
    /// </summary>
    public readonly int YieldCountBuff;
    /// <summary>
    /// 稀有产品变化，可以是负数，1代表 +1%
    /// </summary>
    public readonly int RareRateBuff;
    /// <summary>
    /// 浇水效果变化，可以是负数，1代表1%
    /// </summary>
    public readonly int WaterBuff;
    /// <summary>
    /// 浇水次数变化
    /// </summary>
    public readonly int WaterCountBuff;
    /// <summary>
    /// 施肥效果变化，可以是负数，1代表1%
    /// </summary>
    public readonly int FertilizerBuff;
    /// <summary>
    /// 施肥次数变化，可以是负数
    /// </summary>
    public readonly int FertilizerCountBuff;
    /// <summary>
    /// 虫害概率变化，可以是负数，1代表1%
    /// </summary>
    public readonly int PestRateBuff;
    /// <summary>
    /// 土地描述
    /// </summary>
    public readonly string Desc;
   
    public const int __ID__ = 246169115;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Cost) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "landType:" + LandType + ","
        + "name:" + Name + ","
        + "cost:" + Luban.StringUtil.CollectionToString(Cost) + ","
        + "friendly:" + Luban.StringUtil.CollectionToString(Friendly) + ","
        + "general:" + Luban.StringUtil.CollectionToString(General) + ","
        + "hostile:" + Luban.StringUtil.CollectionToString(Hostile) + ","
        + "growTimeBuff:" + GrowTimeBuff + ","
        + "yieldCountBuff:" + YieldCountBuff + ","
        + "rareRateBuff:" + RareRateBuff + ","
        + "waterBuff:" + WaterBuff + ","
        + "waterCountBuff:" + WaterCountBuff + ","
        + "FertilizerBuff:" + FertilizerBuff + ","
        + "FertilizerCountBuff:" + FertilizerCountBuff + ","
        + "PestRateBuff:" + PestRateBuff + ","
        + "desc:" + Desc + ","
        + "}";
    }
}

}

