
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.farm
{ 
    public enum ELandType
    {
        /// <summary>
        /// 未解锁
        /// </summary>
        LOCK = 0,
        /// <summary>
        /// 解锁中
        /// </summary>
        UNLOCKING = 1,
        /// <summary>
        /// 普通
        /// </summary>
        NORMAL = 2,
        /// <summary>
        /// 黑土地
        /// </summary>
        BLACK = 3,
        /// <summary>
        /// 红土地
        /// </summary>
        RED = 4,
        /// <summary>
        /// 黄土地
        /// </summary>
        YELLOW = 5,
        /// <summary>
        /// 水田地
        /// </summary>
        WATER = 6,
        /// <summary>
        /// 盐碱地
        /// </summary>
        SALT = 7,
    }

} 

