
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class FarmlandChangeType : Luban.BeanBase
{
    public FarmlandChangeType(ByteBuf _buf) 
    {
        LandType = (farm.ELandType)_buf.ReadInt();
        Name = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Cost = new System.Collections.Generic.List<item.ItemExchange>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { item.ItemExchange _e0;  _e0 = item.ItemExchange.DeserializeItemExchange(_buf); Cost.Add(_e0);}}
    }

    public static FarmlandChangeType DeserializeFarmlandChangeType(ByteBuf _buf)
    {
        return new FarmlandChangeType(_buf);
    }

    /// <summary>
    /// 土地类型
    /// </summary>
    public readonly farm.ELandType LandType;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly System.Collections.Generic.List<item.ItemExchange> Cost;
   
    public const int __ID__ = 507707691;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Cost) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "landType:" + LandType + ","
        + "name:" + Name + ","
        + "cost:" + Luban.StringUtil.CollectionToString(Cost) + ","
        + "}";
    }
}

}

