
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class FarmlandUnlock : Luban.BeanBase
{
    public FarmlandUnlock(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        NeedLv = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Cost = new item.ItemExchange[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { item.ItemExchange __e0;__e0 = item.ItemExchange.DeserializeItemExchange(_buf); Cost[__index0] = __e0;}}
        Time = _buf.ReadInt();
    }

    public static FarmlandUnlock DeserializeFarmlandUnlock(ByteBuf _buf)
    {
        return new FarmlandUnlock(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 所需玩家等级
    /// </summary>
    public readonly int NeedLv;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly item.ItemExchange[] Cost;
    /// <summary>
    /// 解锁需要的时间 S
    /// </summary>
    public readonly int Time;
   
    public const int __ID__ = 363682277;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Cost) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "needLv:" + NeedLv + ","
        + "cost:" + Luban.StringUtil.CollectionToString(Cost) + ","
        + "time:" + Time + ","
        + "}";
    }
}

}

