
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Forniture : ItemBase
{
    public Forniture(ByteBuf _buf)  : base(_buf) 
    {
        Kind = (item.EFornitureType)_buf.ReadInt();
    }

    public static Forniture DeserializeForniture(ByteBuf _buf)
    {
        return new Forniture(_buf);
    }

    public readonly item.EFornitureType Kind;
   
    public const int __ID__ = -443389288;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "quality:" + Quality + ","
        + "price:" + Price + ","
        + "desc:" + Desc + ","
        + "kind:" + Kind + ","
        + "}";
    }
}

}

