
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.global
{
/// <summary>
/// 全局
/// </summary>
public partial class TbGlobal
{

     private readonly Global _data;

     public Global Data => _data;

    public TbGlobal(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = Global.DeserializeGlobal(_buf);
    }


    /// <summary>
    /// 玩家初始等级
    /// </summary>
     public int PlayerInitLv => _data.PlayerInitLv;
    /// <summary>
    /// 玩家初始经验
    /// </summary>
     public int PlayerInitExp => _data.PlayerInitExp;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

