
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
public sealed partial class Fertilizer : ItemBase
{
    public Fertilizer(ByteBuf _buf)  : base(_buf) 
    {
        GrowTimeBuff = _buf.ReadInt();
        YieldCountBuff = _buf.ReadInt();
        RareBuff = _buf.ReadInt();
    }

    public static Fertilizer DeserializeFertilizer(ByteBuf _buf)
    {
        return new item.Fertilizer(_buf);
    }

    public readonly int GrowTimeBuff;
    public readonly int YieldCountBuff;
    public readonly int RareBuff;
   
    public const int __ID__ = -1813451363;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "quality:" + Quality + ","
        + "price:" + Price + ","
        + "desc:" + Desc + ","
        + "growTimeBuff:" + GrowTimeBuff + ","
        + "yieldCountBuff:" + YieldCountBuff + ","
        + "rareBuff:" + RareBuff + ","
        + "}";
    }
}

}

