
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
public partial class TbCub
{
    private readonly System.Collections.Generic.Dictionary<int, Cub> _dataMap;
    private readonly System.Collections.Generic.List<Cub> _dataList;
    
    public TbCub(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Cub>();
        _dataList = new System.Collections.Generic.List<Cub>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Cub _v;
            _v = Cub.DeserializeCub(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Cub> DataMap => _dataMap;
    public System.Collections.Generic.List<Cub> DataList => _dataList;

    public Cub GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Cub Get(int key) => _dataMap[key];
    public Cub this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

