
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
/// <summary>
/// 通用道具
/// </summary>
public partial class TbCommonItem
{
    private readonly System.Collections.Generic.Dictionary<int, CommonItem> _dataMap;
    private readonly System.Collections.Generic.List<CommonItem> _dataList;
    
    public TbCommonItem(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, CommonItem>();
        _dataList = new System.Collections.Generic.List<CommonItem>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            CommonItem _v;
            _v = CommonItem.DeserializeCommonItem(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, CommonItem> DataMap => _dataMap;
    public System.Collections.Generic.List<CommonItem> DataList => _dataList;

    public CommonItem GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CommonItem Get(int key) => _dataMap[key];
    public CommonItem this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

