
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
/// <summary>
/// 牧场产物(肉类和副产品)
/// </summary>
public partial class TbRanchProduct
{
    private readonly System.Collections.Generic.Dictionary<int, RanchProduct> _dataMap;
    private readonly System.Collections.Generic.List<RanchProduct> _dataList;
    
    public TbRanchProduct(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, RanchProduct>();
        _dataList = new System.Collections.Generic.List<RanchProduct>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            RanchProduct _v;
            _v = RanchProduct.DeserializeRanchProduct(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, RanchProduct> DataMap => _dataMap;
    public System.Collections.Generic.List<RanchProduct> DataList => _dataList;

    public RanchProduct GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public RanchProduct Get(int key) => _dataMap[key];
    public RanchProduct this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

