
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public abstract partial class ItemBase : Luban.BeanBase
{
    public ItemBase(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Quality = _buf.ReadInt();
        Price = _buf.ReadInt();
        Desc = _buf.ReadString();
    }

    public static ItemBase DeserializeItemBase(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case Forniture.__ID__: return new Forniture(_buf);
            default: throw new SerializationException();
        }
    }

    public readonly int Id;
    public readonly string Name;
    public readonly int Quality;
    public readonly int Price;
    public readonly string Desc;
   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "quality:" + Quality + ","
        + "price:" + Price + ","
        + "desc:" + Desc + ","
        + "}";
    }
}

}

