
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
/// <summary>
/// 鱼类
/// </summary>
public partial class TbFish
{
    private readonly System.Collections.Generic.Dictionary<int, Fish> _dataMap;
    private readonly System.Collections.Generic.List<Fish> _dataList;
    
    public TbFish(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Fish>();
        _dataList = new System.Collections.Generic.List<Fish>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Fish _v;
            _v = Fish.DeserializeFish(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Fish> DataMap => _dataMap;
    public System.Collections.Generic.List<Fish> DataList => _dataList;

    public Fish GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Fish Get(int key) => _dataMap[key];
    public Fish this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

