
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
public sealed partial class ItemExchangeRange : Luban.BeanBase
{
    public ItemExchangeRange(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        MinCount = _buf.ReadInt();
        MaxCount = _buf.ReadInt();
    }

    public static ItemExchangeRange DeserializeItemExchangeRange(ByteBuf _buf)
    {
        return new item.ItemExchangeRange(_buf);
    }

    public readonly int Id;
    public readonly int MinCount;
    public readonly int MaxCount;
   
    public const int __ID__ = 2139521612;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "MinCount:" + MinCount + ","
        + "MaxCount:" + MaxCount + ","
        + "}";
    }
}

}

