
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.item
{ 
    public enum EFornitureType
    {
        /// <summary>
        /// 桌子
        /// </summary>
        DESK = 1,
        /// <summary>
        /// 凳子
        /// </summary>
        BENCH = 2,
    }

} 

