
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.item
{ 
    [System.Flags]
    public enum ECropsType
    {
        /// <summary>
        /// 种子
        /// </summary>
        SEED = 1,
        /// <summary>
        /// 收成物
        /// </summary>
        CROP = 2,
    }

} 

