
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
public partial class TbFry
{
    private readonly System.Collections.Generic.Dictionary<int, Fry> _dataMap;
    private readonly System.Collections.Generic.List<Fry> _dataList;
    
    public TbFry(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Fry>();
        _dataList = new System.Collections.Generic.List<Fry>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Fry _v;
            _v = Fry.DeserializeFry(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Fry> DataMap => _dataMap;
    public System.Collections.Generic.List<Fry> DataList => _dataList;

    public Fry GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Fry Get(int key) => _dataMap[key];
    public Fry this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

