
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.item
{ 
    [System.Flags]
    public enum ETag
    {
        /// <summary>
        /// 蔬菜
        /// </summary>
        Vegetables = 1,
        /// <summary>
        /// 水果
        /// </summary>
        Fruits = 2,
        /// <summary>
        /// 谷类
        /// </summary>
        Grains = 3,
        /// <summary>
        /// 草药
        /// </summary>
        Herbs = 4,
        /// <summary>
        /// 肉畜
        /// </summary>
        MeatLivestock = 5,
        /// <summary>
        /// 禽类
        /// </summary>
        Poultry = 6,
        /// <summary>
        /// 特殊牲畜
        /// </summary>
        SpecialLivestock = 7,
        /// <summary>
        /// 淡水鱼
        /// </summary>
        FreshwaterFish = 8,
        /// <summary>
        /// 咸水鱼
        /// </summary>
        SaltwaterFish = 9,
        /// <summary>
        /// 甲壳类
        /// </summary>
        Crustaceans = 10,
        /// <summary>
        /// 软体类
        /// </summary>
        Mollusks = 11,
        /// <summary>
        /// 奶类
        /// </summary>
        DairyProducts = 12,
        /// <summary>
        /// 蛋类
        /// </summary>
        EggProducts = 13,
        /// <summary>
        /// 肉类
        /// </summary>
        MeatProducts = 14,
        /// <summary>
        /// 饮料
        /// </summary>
        Beverages = 15,
        /// <summary>
        /// 加工品
        /// </summary>
        ProcessedGoods = 16,
        /// <summary>
        /// 蜂制品
        /// </summary>
        BeeProducts = 17,
        /// <summary>
        /// 粪便
        /// </summary>
        Manure = 18,
    }

} 

