
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
/// <summary>
/// 家具
/// </summary>
public partial class TbForniture
{
    private readonly System.Collections.Generic.Dictionary<int, Forniture> _dataMap;
    private readonly System.Collections.Generic.List<Forniture> _dataList;
    
    public TbForniture(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Forniture>();
        _dataList = new System.Collections.Generic.List<Forniture>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Forniture _v;
            _v = Forniture.DeserializeForniture(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Forniture> DataMap => _dataMap;
    public System.Collections.Generic.List<Forniture> DataList => _dataList;

    public Forniture GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Forniture Get(int key) => _dataMap[key];
    public Forniture this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

