
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
public sealed partial class Depester : ItemBase
{
    public Depester(ByteBuf _buf)  : base(_buf) 
    {
        RareRateBuff = _buf.ReadInt();
        PestRateBuff = _buf.ReadInt();
    }

    public static Depester DeserializeDepester(ByteBuf _buf)
    {
        return new item.Depester(_buf);
    }

    public readonly int RareRateBuff;
    public readonly int PestRateBuff;
   
    public const int __ID__ = -242115937;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "quality:" + Quality + ","
        + "price:" + Price + ","
        + "desc:" + Desc + ","
        + "rareRateBuff:" + RareRateBuff + ","
        + "pestRateBuff:" + PestRateBuff + ","
        + "}";
    }
}

}

