
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
public partial class TbFertilizer
{
    private readonly System.Collections.Generic.Dictionary<int, item.Fertilizer> _dataMap;
    private readonly System.Collections.Generic.List<item.Fertilizer> _dataList;
    
    public TbFertilizer(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, item.Fertilizer>();
        _dataList = new System.Collections.Generic.List<item.Fertilizer>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            item.Fertilizer _v;
            _v = item.Fertilizer.DeserializeFertilizer(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, item.Fertilizer> DataMap => _dataMap;
    public System.Collections.Generic.List<item.Fertilizer> DataList => _dataList;

    public item.Fertilizer GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public item.Fertilizer Get(int key) => _dataMap[key];
    public item.Fertilizer this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

