
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class MergeTask : Luban.BeanBase
{
    public MergeTask(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);NeedItem = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); NeedItem[__index0] = __e0;}}
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);NeedCount = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); NeedCount[__index0] = __e0;}}
        RoleImage = _buf.ReadString();
        RefreshTime = _buf.ReadInt();
        LastTaskId = _buf.ReadInt();
    }

    public static MergeTask DeserializeMergeTask(ByteBuf _buf)
    {
        return new MergeTask(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    public readonly int[] NeedItem;
    public readonly int[] NeedCount;
    public readonly string RoleImage;
    /// <summary>
    /// S
    /// </summary>
    public readonly int RefreshTime;
    public readonly int LastTaskId;
   
    public const int __ID__ = -663973443;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "needItem:" + Luban.StringUtil.CollectionToString(NeedItem) + ","
        + "needCount:" + Luban.StringUtil.CollectionToString(NeedCount) + ","
        + "roleImage:" + RoleImage + ","
        + "refreshTime:" + RefreshTime + ","
        + "lastTaskId:" + LastTaskId + ","
        + "}";
    }
}

}

