
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class PlayModule : Luban.BeanBase
{
    public PlayModule(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Lv = _buf.ReadInt();
    }

    public static PlayModule DeserializePlayModule(ByteBuf _buf)
    {
        return new PlayModule(_buf);
    }

    /// <summary>
    /// 模块Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 模块名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 解锁等级
    /// </summary>
    public readonly int Lv;
   
    public const int __ID__ = -895040800;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "name:" + Name + ","
        + "lv:" + Lv + ","
        + "}";
    }
}

}

