
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Seasoning : ItemBase
{
    public Seasoning(ByteBuf _buf)  : base(_buf) 
    {
    }

    public static Seasoning DeserializeSeasoning(ByteBuf _buf)
    {
        return new Seasoning(_buf);
    }

   
    public const int __ID__ = -472891905;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "quality:" + Quality + ","
        + "price:" + Price + ","
        + "desc:" + Desc + ","
        + "}";
    }
}

}

