
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.site
{
/// <summary>
/// 农场田地解锁条件
/// </summary>
public partial class TbFarmlandUnlock
{
    private readonly System.Collections.Generic.Dictionary<int, FarmlandUnlock> _dataMap;
    private readonly System.Collections.Generic.List<FarmlandUnlock> _dataList;
    
    public TbFarmlandUnlock(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, FarmlandUnlock>();
        _dataList = new System.Collections.Generic.List<FarmlandUnlock>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            FarmlandUnlock _v;
            _v = FarmlandUnlock.DeserializeFarmlandUnlock(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, FarmlandUnlock> DataMap => _dataMap;
    public System.Collections.Generic.List<FarmlandUnlock> DataList => _dataList;

    public FarmlandUnlock GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public FarmlandUnlock Get(int key) => _dataMap[key];
    public FarmlandUnlock this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

