
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.site
{
public partial class TbFarmlandChangeType
{
    private readonly System.Collections.Generic.Dictionary<farm.ELandType, FarmlandChangeType> _dataMap;
    private readonly System.Collections.Generic.List<FarmlandChangeType> _dataList;
    
    public TbFarmlandChangeType(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<farm.ELandType, FarmlandChangeType>();
        _dataList = new System.Collections.Generic.List<FarmlandChangeType>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            FarmlandChangeType _v;
            _v = FarmlandChangeType.DeserializeFarmlandChangeType(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.LandType, _v);
        }
    }

    public System.Collections.Generic.Dictionary<farm.ELandType, FarmlandChangeType> DataMap => _dataMap;
    public System.Collections.Generic.List<FarmlandChangeType> DataList => _dataList;

    public FarmlandChangeType GetOrDefault(farm.ELandType key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public FarmlandChangeType Get(farm.ELandType key) => _dataMap[key];
    public FarmlandChangeType this[farm.ELandType key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

