
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace GameConfig
{
public partial class Tables
{
    /// <summary>
    /// 全局
    /// </summary>
    public global.TbGlobal TbGlobal {get; }
    public item.TbItemBase TbItemBase {get; }
    /// <summary>
    /// 通用道具
    /// </summary>
    public item.TbCommonItem TbCommonItem {get; }
    public site.TbFarmlandType TbFarmlandType {get; }
    /// <summary>
    /// 农场田地解锁条件
    /// </summary>
    public site.TbFarmlandUnlock TbFarmlandUnlock {get; }
    public network.TbErrorCode TbErrorCode {get; }
    public common.TbModule TbModule {get; }
    /// <summary>
    /// 农作物
    /// </summary>
    public item.TbCrops TbCrops {get; }
    public item.TbSeed TbSeed {get; }
    public item.TbFertilizer TbFertilizer {get; }
    public item.TbDepester TbDepester {get; }
    public item.TbCub TbCub {get; }
    /// <summary>
    /// 牲畜
    /// </summary>
    public item.TbLivestock TbLivestock {get; }
    /// <summary>
    /// 牧场产物(肉类和副产品)
    /// </summary>
    public item.TbRanchProduct TbRanchProduct {get; }
    public item.TbByProduct TbByProduct {get; }
    public item.TbFry TbFry {get; }
    /// <summary>
    /// 鱼类
    /// </summary>
    public item.TbFish TbFish {get; }
    public item.TbFishProduct TbFishProduct {get; }
    /// <summary>
    /// 调味品
    /// </summary>
    public item.TbSeasoning TbSeasoning {get; }
    /// <summary>
    /// 雇员
    /// </summary>
    public character.TbWorker TbWorker {get; }
    /// <summary>
    /// 家具
    /// </summary>
    public item.TbForniture TbForniture {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbGlobal = new global.TbGlobal(loader("global_tbglobal"));
        TbItemBase = new item.TbItemBase(loader("item_tbitembase"));
        TbCommonItem = new item.TbCommonItem(loader("item_tbcommonitem"));
        TbFarmlandType = new site.TbFarmlandType(loader("site_tbfarmlandtype"));
        TbFarmlandUnlock = new site.TbFarmlandUnlock(loader("site_tbfarmlandunlock"));
        TbErrorCode = new network.TbErrorCode(loader("network_tberrorcode"));
        TbModule = new common.TbModule(loader("common_tbmodule"));
        TbCrops = new item.TbCrops(loader("item_tbcrops"));
        TbSeed = new item.TbSeed(loader("item_tbseed"));
        TbFertilizer = new item.TbFertilizer(loader("item_tbfertilizer"));
        TbDepester = new item.TbDepester(loader("item_tbdepester"));
        TbCub = new item.TbCub(loader("item_tbcub"));
        TbLivestock = new item.TbLivestock(loader("item_tblivestock"));
        TbRanchProduct = new item.TbRanchProduct(loader("item_tbranchproduct"));
        TbByProduct = new item.TbByProduct(loader("item_tbbyproduct"));
        TbFry = new item.TbFry(loader("item_tbfry"));
        TbFish = new item.TbFish(loader("item_tbfish"));
        TbFishProduct = new item.TbFishProduct(loader("item_tbfishproduct"));
        TbSeasoning = new item.TbSeasoning(loader("item_tbseasoning"));
        TbWorker = new character.TbWorker(loader("character_tbworker"));
        TbForniture = new item.TbForniture(loader("item_tbforniture"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbGlobal.ResolveRef(this);
        TbItemBase.ResolveRef(this);
        TbCommonItem.ResolveRef(this);
        TbFarmlandType.ResolveRef(this);
        TbFarmlandUnlock.ResolveRef(this);
        TbErrorCode.ResolveRef(this);
        TbModule.ResolveRef(this);
        TbCrops.ResolveRef(this);
        TbSeed.ResolveRef(this);
        TbFertilizer.ResolveRef(this);
        TbDepester.ResolveRef(this);
        TbCub.ResolveRef(this);
        TbLivestock.ResolveRef(this);
        TbRanchProduct.ResolveRef(this);
        TbByProduct.ResolveRef(this);
        TbFry.ResolveRef(this);
        TbFish.ResolveRef(this);
        TbFishProduct.ResolveRef(this);
        TbSeasoning.ResolveRef(this);
        TbWorker.ResolveRef(this);
        TbForniture.ResolveRef(this);
    }
	
	public List<string> GetTableNames()
    {
        return new List<string>
        {
            "global_tbglobal",
            "item_tbitembase",
            "item_tbcommonitem",
            "site_tbfarmlandtype",
            "site_tbfarmlandunlock",
            "network_tberrorcode",
            "common_tbmodule",
            "item_tbcrops",
            "item_tbseed",
            "item_tbfertilizer",
            "item_tbdepester",
            "item_tbcub",
            "item_tblivestock",
            "item_tbranchproduct",
            "item_tbbyproduct",
            "item_tbfry",
            "item_tbfish",
            "item_tbfishproduct",
            "item_tbseasoning",
            "character_tbworker",
            "item_tbforniture",
        };
    }
}

}
