
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace GameConfig
{
public partial class Tables
{
    public task.TbMergeTask TbMergeTask {get; }
    public item.TbItem TbItem {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbMergeTask = new task.TbMergeTask(loader("task_tbmergetask"));
        TbItem = new item.TbItem(loader("item_tbitem"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbMergeTask.ResolveRef(this);
        TbItem.ResolveRef(this);
    }
	
	public List<string> GetTableNames()
    {
        return new List<string>
        {
            "task_tbmergetask",
            "item_tbitem",
        };
    }
}

}
