
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.task
{
public partial class TbMergeTask
{
    private readonly System.Collections.Generic.Dictionary<int, MergeTask> _dataMap;
    private readonly System.Collections.Generic.List<MergeTask> _dataList;
    
    public TbMergeTask(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, MergeTask>();
        _dataList = new System.Collections.Generic.List<MergeTask>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            MergeTask _v;
            _v = MergeTask.DeserializeMergeTask(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, MergeTask> DataMap => _dataMap;
    public System.Collections.Generic.List<MergeTask> DataList => _dataList;

    public MergeTask GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public MergeTask Get(int key) => _dataMap[key];
    public MergeTask this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

